// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ox.proto

package ox_idl

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TicketRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TicketRequest) Reset()         { *m = TicketRequest{} }
func (m *TicketRequest) String() string { return proto.CompactTextString(m) }
func (*TicketRequest) ProtoMessage()    {}
func (*TicketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ox_e51317145b603e82, []int{0}
}
func (m *TicketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TicketRequest.Unmarshal(m, b)
}
func (m *TicketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TicketRequest.Marshal(b, m, deterministic)
}
func (dst *TicketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TicketRequest.Merge(dst, src)
}
func (m *TicketRequest) XXX_Size() int {
	return xxx_messageInfo_TicketRequest.Size(m)
}
func (m *TicketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TicketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TicketRequest proto.InternalMessageInfo

func (m *TicketRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type TicketStatsRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	TicketID             string   `protobuf:"bytes,2,opt,name=ticketID,proto3" json:"ticketID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TicketStatsRequest) Reset()         { *m = TicketStatsRequest{} }
func (m *TicketStatsRequest) String() string { return proto.CompactTextString(m) }
func (*TicketStatsRequest) ProtoMessage()    {}
func (*TicketStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ox_e51317145b603e82, []int{1}
}
func (m *TicketStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TicketStatsRequest.Unmarshal(m, b)
}
func (m *TicketStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TicketStatsRequest.Marshal(b, m, deterministic)
}
func (dst *TicketStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TicketStatsRequest.Merge(dst, src)
}
func (m *TicketStatsRequest) XXX_Size() int {
	return xxx_messageInfo_TicketStatsRequest.Size(m)
}
func (m *TicketStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TicketStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TicketStatsRequest proto.InternalMessageInfo

func (m *TicketStatsRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *TicketStatsRequest) GetTicketID() string {
	if m != nil {
		return m.TicketID
	}
	return ""
}

type Ticket struct {
	TicketID             string   `protobuf:"bytes,1,opt,name=ticketID,proto3" json:"ticketID,omitempty"`
	EventID              string   `protobuf:"bytes,2,opt,name=eventID,proto3" json:"eventID,omitempty"`
	UserID               string   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	Company              string   `protobuf:"bytes,4,opt,name=company,proto3" json:"company,omitempty"`
	VenueCity            string   `protobuf:"bytes,5,opt,name=venueCity,proto3" json:"venueCity,omitempty"`
	VenueName            string   `protobuf:"bytes,6,opt,name=venueName,proto3" json:"venueName,omitempty"`
	StartDate            string   `protobuf:"bytes,7,opt,name=startDate,proto3" json:"startDate,omitempty"`
	StartTime            string   `protobuf:"bytes,8,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EventName            string   `protobuf:"bytes,9,opt,name=eventName,proto3" json:"eventName,omitempty"`
	Amount               float64  `protobuf:"fixed64,10,opt,name=amount,proto3" json:"amount,omitempty"`
	Image                string   `protobuf:"bytes,11,opt,name=image,proto3" json:"image,omitempty"`
	Logo                 string   `protobuf:"bytes,12,opt,name=logo,proto3" json:"logo,omitempty"`
	PurchasedOn          int64    `protobuf:"varint,13,opt,name=purchasedOn,proto3" json:"purchasedOn,omitempty"`
	TimeZone             string   `protobuf:"bytes,14,opt,name=timeZone,proto3" json:"timeZone,omitempty"`
	Zone                 string   `protobuf:"bytes,15,opt,name=zone,proto3" json:"zone,omitempty"`
	Visitors             int32    `protobuf:"varint,16,opt,name=visitors,proto3" json:"visitors,omitempty"`
	Attendees            int32    `protobuf:"varint,17,opt,name=attendees,proto3" json:"attendees,omitempty"`
	EndDate              string   `protobuf:"bytes,18,opt,name=endDate,proto3" json:"endDate,omitempty"`
	EndTime              string   `protobuf:"bytes,19,opt,name=endTime,proto3" json:"endTime,omitempty"`
	TicketTimeZone       string   `protobuf:"bytes,20,opt,name=ticketTimeZone,proto3" json:"ticketTimeZone,omitempty"`
	TicketZone           string   `protobuf:"bytes,21,opt,name=ticketZone,proto3" json:"ticketZone,omitempty"`
	Currency             string   `protobuf:"bytes,22,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ticket) Reset()         { *m = Ticket{} }
func (m *Ticket) String() string { return proto.CompactTextString(m) }
func (*Ticket) ProtoMessage()    {}
func (*Ticket) Descriptor() ([]byte, []int) {
	return fileDescriptor_ox_e51317145b603e82, []int{2}
}
func (m *Ticket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ticket.Unmarshal(m, b)
}
func (m *Ticket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ticket.Marshal(b, m, deterministic)
}
func (dst *Ticket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ticket.Merge(dst, src)
}
func (m *Ticket) XXX_Size() int {
	return xxx_messageInfo_Ticket.Size(m)
}
func (m *Ticket) XXX_DiscardUnknown() {
	xxx_messageInfo_Ticket.DiscardUnknown(m)
}

var xxx_messageInfo_Ticket proto.InternalMessageInfo

func (m *Ticket) GetTicketID() string {
	if m != nil {
		return m.TicketID
	}
	return ""
}

func (m *Ticket) GetEventID() string {
	if m != nil {
		return m.EventID
	}
	return ""
}

func (m *Ticket) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Ticket) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *Ticket) GetVenueCity() string {
	if m != nil {
		return m.VenueCity
	}
	return ""
}

func (m *Ticket) GetVenueName() string {
	if m != nil {
		return m.VenueName
	}
	return ""
}

func (m *Ticket) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *Ticket) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *Ticket) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

func (m *Ticket) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Ticket) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Ticket) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *Ticket) GetPurchasedOn() int64 {
	if m != nil {
		return m.PurchasedOn
	}
	return 0
}

func (m *Ticket) GetTimeZone() string {
	if m != nil {
		return m.TimeZone
	}
	return ""
}

func (m *Ticket) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *Ticket) GetVisitors() int32 {
	if m != nil {
		return m.Visitors
	}
	return 0
}

func (m *Ticket) GetAttendees() int32 {
	if m != nil {
		return m.Attendees
	}
	return 0
}

func (m *Ticket) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *Ticket) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *Ticket) GetTicketTimeZone() string {
	if m != nil {
		return m.TicketTimeZone
	}
	return ""
}

func (m *Ticket) GetTicketZone() string {
	if m != nil {
		return m.TicketZone
	}
	return ""
}

func (m *Ticket) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type AttendeesStatus struct {
	VisitorCount         int32    `protobuf:"varint,1,opt,name=visitorCount,proto3" json:"visitorCount,omitempty"`
	AttendeeCount        int32    `protobuf:"varint,2,opt,name=attendeeCount,proto3" json:"attendeeCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttendeesStatus) Reset()         { *m = AttendeesStatus{} }
func (m *AttendeesStatus) String() string { return proto.CompactTextString(m) }
func (*AttendeesStatus) ProtoMessage()    {}
func (*AttendeesStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_ox_e51317145b603e82, []int{3}
}
func (m *AttendeesStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttendeesStatus.Unmarshal(m, b)
}
func (m *AttendeesStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttendeesStatus.Marshal(b, m, deterministic)
}
func (dst *AttendeesStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttendeesStatus.Merge(dst, src)
}
func (m *AttendeesStatus) XXX_Size() int {
	return xxx_messageInfo_AttendeesStatus.Size(m)
}
func (m *AttendeesStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_AttendeesStatus.DiscardUnknown(m)
}

var xxx_messageInfo_AttendeesStatus proto.InternalMessageInfo

func (m *AttendeesStatus) GetVisitorCount() int32 {
	if m != nil {
		return m.VisitorCount
	}
	return 0
}

func (m *AttendeesStatus) GetAttendeeCount() int32 {
	if m != nil {
		return m.AttendeeCount
	}
	return 0
}

type ConfirmAttendeeTicket struct {
	TicketId             string   `protobuf:"bytes,1,opt,name=ticketId,proto3" json:"ticketId,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmAttendeeTicket) Reset()         { *m = ConfirmAttendeeTicket{} }
func (m *ConfirmAttendeeTicket) String() string { return proto.CompactTextString(m) }
func (*ConfirmAttendeeTicket) ProtoMessage()    {}
func (*ConfirmAttendeeTicket) Descriptor() ([]byte, []int) {
	return fileDescriptor_ox_e51317145b603e82, []int{4}
}
func (m *ConfirmAttendeeTicket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmAttendeeTicket.Unmarshal(m, b)
}
func (m *ConfirmAttendeeTicket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmAttendeeTicket.Marshal(b, m, deterministic)
}
func (dst *ConfirmAttendeeTicket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmAttendeeTicket.Merge(dst, src)
}
func (m *ConfirmAttendeeTicket) XXX_Size() int {
	return xxx_messageInfo_ConfirmAttendeeTicket.Size(m)
}
func (m *ConfirmAttendeeTicket) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmAttendeeTicket.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmAttendeeTicket proto.InternalMessageInfo

func (m *ConfirmAttendeeTicket) GetTicketId() string {
	if m != nil {
		return m.TicketId
	}
	return ""
}

func (m *ConfirmAttendeeTicket) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Response struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ox_e51317145b603e82, []int{5}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PrintTicketRequest struct {
	TicketId             string   `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	AttendeeId           string   `protobuf:"bytes,2,opt,name=attendee_id,json=attendeeId,proto3" json:"attendee_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrintTicketRequest) Reset()         { *m = PrintTicketRequest{} }
func (m *PrintTicketRequest) String() string { return proto.CompactTextString(m) }
func (*PrintTicketRequest) ProtoMessage()    {}
func (*PrintTicketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ox_e51317145b603e82, []int{6}
}
func (m *PrintTicketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrintTicketRequest.Unmarshal(m, b)
}
func (m *PrintTicketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrintTicketRequest.Marshal(b, m, deterministic)
}
func (dst *PrintTicketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrintTicketRequest.Merge(dst, src)
}
func (m *PrintTicketRequest) XXX_Size() int {
	return xxx_messageInfo_PrintTicketRequest.Size(m)
}
func (m *PrintTicketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrintTicketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrintTicketRequest proto.InternalMessageInfo

func (m *PrintTicketRequest) GetTicketId() string {
	if m != nil {
		return m.TicketId
	}
	return ""
}

func (m *PrintTicketRequest) GetAttendeeId() string {
	if m != nil {
		return m.AttendeeId
	}
	return ""
}

type EventInfo struct {
	EventName            string   `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	StartDate            string   `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	StartTime            string   `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Venue                string   `protobuf:"bytes,4,opt,name=venue,proto3" json:"venue,omitempty"`
	Organizer            string   `protobuf:"bytes,5,opt,name=organizer,proto3" json:"organizer,omitempty"`
	TicketName           string   `protobuf:"bytes,6,opt,name=ticket_name,json=ticketName,proto3" json:"ticket_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventInfo) Reset()         { *m = EventInfo{} }
func (m *EventInfo) String() string { return proto.CompactTextString(m) }
func (*EventInfo) ProtoMessage()    {}
func (*EventInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ox_e51317145b603e82, []int{7}
}
func (m *EventInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventInfo.Unmarshal(m, b)
}
func (m *EventInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventInfo.Marshal(b, m, deterministic)
}
func (dst *EventInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventInfo.Merge(dst, src)
}
func (m *EventInfo) XXX_Size() int {
	return xxx_messageInfo_EventInfo.Size(m)
}
func (m *EventInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EventInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EventInfo proto.InternalMessageInfo

func (m *EventInfo) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

func (m *EventInfo) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *EventInfo) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *EventInfo) GetVenue() string {
	if m != nil {
		return m.Venue
	}
	return ""
}

func (m *EventInfo) GetOrganizer() string {
	if m != nil {
		return m.Organizer
	}
	return ""
}

func (m *EventInfo) GetTicketName() string {
	if m != nil {
		return m.TicketName
	}
	return ""
}

type TicketInfo struct {
	EventId              string    `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	PurchasedBy          string    `protobuf:"bytes,2,opt,name=purchased_by,json=purchasedBy,proto3" json:"purchased_by,omitempty"`
	PurchasedOn          int64     `protobuf:"varint,3,opt,name=purchased_on,json=purchasedOn,proto3" json:"purchased_on,omitempty"`
	Attendee             *Attendee `protobuf:"bytes,4,opt,name=attendee,proto3" json:"attendee,omitempty"`
	TicketNumber         string    `protobuf:"bytes,5,opt,name=ticket_number,json=ticketNumber,proto3" json:"ticket_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TicketInfo) Reset()         { *m = TicketInfo{} }
func (m *TicketInfo) String() string { return proto.CompactTextString(m) }
func (*TicketInfo) ProtoMessage()    {}
func (*TicketInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ox_e51317145b603e82, []int{8}
}
func (m *TicketInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TicketInfo.Unmarshal(m, b)
}
func (m *TicketInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TicketInfo.Marshal(b, m, deterministic)
}
func (dst *TicketInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TicketInfo.Merge(dst, src)
}
func (m *TicketInfo) XXX_Size() int {
	return xxx_messageInfo_TicketInfo.Size(m)
}
func (m *TicketInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TicketInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TicketInfo proto.InternalMessageInfo

func (m *TicketInfo) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *TicketInfo) GetPurchasedBy() string {
	if m != nil {
		return m.PurchasedBy
	}
	return ""
}

func (m *TicketInfo) GetPurchasedOn() int64 {
	if m != nil {
		return m.PurchasedOn
	}
	return 0
}

func (m *TicketInfo) GetAttendee() *Attendee {
	if m != nil {
		return m.Attendee
	}
	return nil
}

func (m *TicketInfo) GetTicketNumber() string {
	if m != nil {
		return m.TicketNumber
	}
	return ""
}

type Attendee struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attendee) Reset()         { *m = Attendee{} }
func (m *Attendee) String() string { return proto.CompactTextString(m) }
func (*Attendee) ProtoMessage()    {}
func (*Attendee) Descriptor() ([]byte, []int) {
	return fileDescriptor_ox_e51317145b603e82, []int{9}
}
func (m *Attendee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attendee.Unmarshal(m, b)
}
func (m *Attendee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attendee.Marshal(b, m, deterministic)
}
func (dst *Attendee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attendee.Merge(dst, src)
}
func (m *Attendee) XXX_Size() int {
	return xxx_messageInfo_Attendee.Size(m)
}
func (m *Attendee) XXX_DiscardUnknown() {
	xxx_messageInfo_Attendee.DiscardUnknown(m)
}

var xxx_messageInfo_Attendee proto.InternalMessageInfo

func (m *Attendee) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Attendee) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PrintTicketResponse struct {
	Event                *EventInfo  `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Ticket               *TicketInfo `protobuf:"bytes,2,opt,name=ticket,proto3" json:"ticket,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PrintTicketResponse) Reset()         { *m = PrintTicketResponse{} }
func (m *PrintTicketResponse) String() string { return proto.CompactTextString(m) }
func (*PrintTicketResponse) ProtoMessage()    {}
func (*PrintTicketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ox_e51317145b603e82, []int{10}
}
func (m *PrintTicketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrintTicketResponse.Unmarshal(m, b)
}
func (m *PrintTicketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrintTicketResponse.Marshal(b, m, deterministic)
}
func (dst *PrintTicketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrintTicketResponse.Merge(dst, src)
}
func (m *PrintTicketResponse) XXX_Size() int {
	return xxx_messageInfo_PrintTicketResponse.Size(m)
}
func (m *PrintTicketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrintTicketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrintTicketResponse proto.InternalMessageInfo

func (m *PrintTicketResponse) GetEvent() *EventInfo {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *PrintTicketResponse) GetTicket() *TicketInfo {
	if m != nil {
		return m.Ticket
	}
	return nil
}

type PrintAllTicketsRequest struct {
	TicketId             string   `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrintAllTicketsRequest) Reset()         { *m = PrintAllTicketsRequest{} }
func (m *PrintAllTicketsRequest) String() string { return proto.CompactTextString(m) }
func (*PrintAllTicketsRequest) ProtoMessage()    {}
func (*PrintAllTicketsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ox_e51317145b603e82, []int{11}
}
func (m *PrintAllTicketsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrintAllTicketsRequest.Unmarshal(m, b)
}
func (m *PrintAllTicketsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrintAllTicketsRequest.Marshal(b, m, deterministic)
}
func (dst *PrintAllTicketsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrintAllTicketsRequest.Merge(dst, src)
}
func (m *PrintAllTicketsRequest) XXX_Size() int {
	return xxx_messageInfo_PrintAllTicketsRequest.Size(m)
}
func (m *PrintAllTicketsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrintAllTicketsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrintAllTicketsRequest proto.InternalMessageInfo

func (m *PrintAllTicketsRequest) GetTicketId() string {
	if m != nil {
		return m.TicketId
	}
	return ""
}

type AllTicketsInfo struct {
	EventId              string      `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	PurchasedBy          string      `protobuf:"bytes,2,opt,name=purchased_by,json=purchasedBy,proto3" json:"purchased_by,omitempty"`
	PurchasedOn          int64       `protobuf:"varint,3,opt,name=purchased_on,json=purchasedOn,proto3" json:"purchased_on,omitempty"`
	Attendees            []*Attendee `protobuf:"bytes,4,rep,name=attendees,proto3" json:"attendees,omitempty"`
	TicketNumber         string      `protobuf:"bytes,5,opt,name=ticket_number,json=ticketNumber,proto3" json:"ticket_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AllTicketsInfo) Reset()         { *m = AllTicketsInfo{} }
func (m *AllTicketsInfo) String() string { return proto.CompactTextString(m) }
func (*AllTicketsInfo) ProtoMessage()    {}
func (*AllTicketsInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ox_e51317145b603e82, []int{12}
}
func (m *AllTicketsInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllTicketsInfo.Unmarshal(m, b)
}
func (m *AllTicketsInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllTicketsInfo.Marshal(b, m, deterministic)
}
func (dst *AllTicketsInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllTicketsInfo.Merge(dst, src)
}
func (m *AllTicketsInfo) XXX_Size() int {
	return xxx_messageInfo_AllTicketsInfo.Size(m)
}
func (m *AllTicketsInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AllTicketsInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AllTicketsInfo proto.InternalMessageInfo

func (m *AllTicketsInfo) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *AllTicketsInfo) GetPurchasedBy() string {
	if m != nil {
		return m.PurchasedBy
	}
	return ""
}

func (m *AllTicketsInfo) GetPurchasedOn() int64 {
	if m != nil {
		return m.PurchasedOn
	}
	return 0
}

func (m *AllTicketsInfo) GetAttendees() []*Attendee {
	if m != nil {
		return m.Attendees
	}
	return nil
}

func (m *AllTicketsInfo) GetTicketNumber() string {
	if m != nil {
		return m.TicketNumber
	}
	return ""
}

type PrintAllTicketsResponse struct {
	Event                *EventInfo      `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Ticket               *AllTicketsInfo `protobuf:"bytes,2,opt,name=ticket,proto3" json:"ticket,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PrintAllTicketsResponse) Reset()         { *m = PrintAllTicketsResponse{} }
func (m *PrintAllTicketsResponse) String() string { return proto.CompactTextString(m) }
func (*PrintAllTicketsResponse) ProtoMessage()    {}
func (*PrintAllTicketsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ox_e51317145b603e82, []int{13}
}
func (m *PrintAllTicketsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrintAllTicketsResponse.Unmarshal(m, b)
}
func (m *PrintAllTicketsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrintAllTicketsResponse.Marshal(b, m, deterministic)
}
func (dst *PrintAllTicketsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrintAllTicketsResponse.Merge(dst, src)
}
func (m *PrintAllTicketsResponse) XXX_Size() int {
	return xxx_messageInfo_PrintAllTicketsResponse.Size(m)
}
func (m *PrintAllTicketsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrintAllTicketsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrintAllTicketsResponse proto.InternalMessageInfo

func (m *PrintAllTicketsResponse) GetEvent() *EventInfo {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *PrintAllTicketsResponse) GetTicket() *AllTicketsInfo {
	if m != nil {
		return m.Ticket
	}
	return nil
}

func init() {
	proto.RegisterType((*TicketRequest)(nil), "ox_idl.TicketRequest")
	proto.RegisterType((*TicketStatsRequest)(nil), "ox_idl.TicketStatsRequest")
	proto.RegisterType((*Ticket)(nil), "ox_idl.Ticket")
	proto.RegisterType((*AttendeesStatus)(nil), "ox_idl.AttendeesStatus")
	proto.RegisterType((*ConfirmAttendeeTicket)(nil), "ox_idl.ConfirmAttendeeTicket")
	proto.RegisterType((*Response)(nil), "ox_idl.Response")
	proto.RegisterType((*PrintTicketRequest)(nil), "ox_idl.PrintTicketRequest")
	proto.RegisterType((*EventInfo)(nil), "ox_idl.EventInfo")
	proto.RegisterType((*TicketInfo)(nil), "ox_idl.TicketInfo")
	proto.RegisterType((*Attendee)(nil), "ox_idl.Attendee")
	proto.RegisterType((*PrintTicketResponse)(nil), "ox_idl.PrintTicketResponse")
	proto.RegisterType((*PrintAllTicketsRequest)(nil), "ox_idl.PrintAllTicketsRequest")
	proto.RegisterType((*AllTicketsInfo)(nil), "ox_idl.AllTicketsInfo")
	proto.RegisterType((*PrintAllTicketsResponse)(nil), "ox_idl.PrintAllTicketsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OXClient is the client API for OX service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OXClient interface {
	GetTicketsByID(ctx context.Context, in *TicketRequest, opts ...grpc.CallOption) (OX_GetTicketsByIDClient, error)
	GetAttendeesStatus(ctx context.Context, in *TicketRequest, opts ...grpc.CallOption) (*AttendeesStatus, error)
	ConfirmAttendee(ctx context.Context, in *ConfirmAttendeeTicket, opts ...grpc.CallOption) (*Response, error)
	PrintAttendeeTicket(ctx context.Context, in *PrintTicketRequest, opts ...grpc.CallOption) (*PrintTicketResponse, error)
	PrintAllAttendeeTickets(ctx context.Context, in *PrintAllTicketsRequest, opts ...grpc.CallOption) (*PrintAllTicketsResponse, error)
}

type oXClient struct {
	cc *grpc.ClientConn
}

func NewOXClient(cc *grpc.ClientConn) OXClient {
	return &oXClient{cc}
}

func (c *oXClient) GetTicketsByID(ctx context.Context, in *TicketRequest, opts ...grpc.CallOption) (OX_GetTicketsByIDClient, error) {
	stream, err := c.cc.NewStream(ctx, &_OX_serviceDesc.Streams[0], "/ox_idl.OX/GetTicketsByID", opts...)
	if err != nil {
		return nil, err
	}
	x := &oXGetTicketsByIDClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OX_GetTicketsByIDClient interface {
	Recv() (*Ticket, error)
	grpc.ClientStream
}

type oXGetTicketsByIDClient struct {
	grpc.ClientStream
}

func (x *oXGetTicketsByIDClient) Recv() (*Ticket, error) {
	m := new(Ticket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *oXClient) GetAttendeesStatus(ctx context.Context, in *TicketRequest, opts ...grpc.CallOption) (*AttendeesStatus, error) {
	out := new(AttendeesStatus)
	err := c.cc.Invoke(ctx, "/ox_idl.OX/GetAttendeesStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oXClient) ConfirmAttendee(ctx context.Context, in *ConfirmAttendeeTicket, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ox_idl.OX/ConfirmAttendee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oXClient) PrintAttendeeTicket(ctx context.Context, in *PrintTicketRequest, opts ...grpc.CallOption) (*PrintTicketResponse, error) {
	out := new(PrintTicketResponse)
	err := c.cc.Invoke(ctx, "/ox_idl.OX/PrintAttendeeTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oXClient) PrintAllAttendeeTickets(ctx context.Context, in *PrintAllTicketsRequest, opts ...grpc.CallOption) (*PrintAllTicketsResponse, error) {
	out := new(PrintAllTicketsResponse)
	err := c.cc.Invoke(ctx, "/ox_idl.OX/PrintAllAttendeeTickets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OXServer is the server API for OX service.
type OXServer interface {
	GetTicketsByID(*TicketRequest, OX_GetTicketsByIDServer) error
	GetAttendeesStatus(context.Context, *TicketRequest) (*AttendeesStatus, error)
	ConfirmAttendee(context.Context, *ConfirmAttendeeTicket) (*Response, error)
	PrintAttendeeTicket(context.Context, *PrintTicketRequest) (*PrintTicketResponse, error)
	PrintAllAttendeeTickets(context.Context, *PrintAllTicketsRequest) (*PrintAllTicketsResponse, error)
}

func RegisterOXServer(s *grpc.Server, srv OXServer) {
	s.RegisterService(&_OX_serviceDesc, srv)
}

func _OX_GetTicketsByID_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TicketRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OXServer).GetTicketsByID(m, &oXGetTicketsByIDServer{stream})
}

type OX_GetTicketsByIDServer interface {
	Send(*Ticket) error
	grpc.ServerStream
}

type oXGetTicketsByIDServer struct {
	grpc.ServerStream
}

func (x *oXGetTicketsByIDServer) Send(m *Ticket) error {
	return x.ServerStream.SendMsg(m)
}

func _OX_GetAttendeesStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OXServer).GetAttendeesStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ox_idl.OX/GetAttendeesStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OXServer).GetAttendeesStatus(ctx, req.(*TicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OX_ConfirmAttendee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmAttendeeTicket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OXServer).ConfirmAttendee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ox_idl.OX/ConfirmAttendee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OXServer).ConfirmAttendee(ctx, req.(*ConfirmAttendeeTicket))
	}
	return interceptor(ctx, in, info, handler)
}

func _OX_PrintAttendeeTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OXServer).PrintAttendeeTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ox_idl.OX/PrintAttendeeTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OXServer).PrintAttendeeTicket(ctx, req.(*PrintTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OX_PrintAllAttendeeTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintAllTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OXServer).PrintAllAttendeeTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ox_idl.OX/PrintAllAttendeeTickets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OXServer).PrintAllAttendeeTickets(ctx, req.(*PrintAllTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OX_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ox_idl.OX",
	HandlerType: (*OXServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAttendeesStatus",
			Handler:    _OX_GetAttendeesStatus_Handler,
		},
		{
			MethodName: "ConfirmAttendee",
			Handler:    _OX_ConfirmAttendee_Handler,
		},
		{
			MethodName: "PrintAttendeeTicket",
			Handler:    _OX_PrintAttendeeTicket_Handler,
		},
		{
			MethodName: "PrintAllAttendeeTickets",
			Handler:    _OX_PrintAllAttendeeTickets_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTicketsByID",
			Handler:       _OX_GetTicketsByID_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ox.proto",
}

func init() { proto.RegisterFile("ox.proto", fileDescriptor_ox_e51317145b603e82) }

var fileDescriptor_ox_e51317145b603e82 = []byte{
	// 884 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x5f, 0x6f, 0x1b, 0x45,
	0x10, 0xcf, 0x39, 0xb1, 0x63, 0x8f, 0x13, 0xa7, 0xdd, 0x26, 0xe9, 0xe2, 0x92, 0xc6, 0x2c, 0x08,
	0x2c, 0x84, 0x2c, 0x64, 0xe0, 0x09, 0x5e, 0xda, 0x18, 0x8a, 0x85, 0x44, 0xab, 0x23, 0x0f, 0x08,
	0x90, 0xac, 0x8b, 0x6f, 0x1b, 0x0e, 0x7c, 0x7b, 0xe6, 0x76, 0x2f, 0xaa, 0xfb, 0xdd, 0x90, 0x78,
	0xe2, 0xd3, 0xf0, 0x1d, 0x40, 0x3b, 0xfb, 0xe7, 0xfe, 0x38, 0x95, 0xc2, 0x4b, 0xdf, 0x3c, 0x33,
	0xbf, 0x9b, 0x9d, 0xf9, 0xcd, 0x6f, 0x46, 0x86, 0x6e, 0xf6, 0x6a, 0xb2, 0xce, 0x33, 0x95, 0x91,
	0x4e, 0xf6, 0x6a, 0x91, 0xc4, 0x2b, 0x76, 0x0e, 0x87, 0x97, 0xc9, 0xf2, 0x77, 0xae, 0x42, 0xfe,
	0x47, 0xc1, 0xa5, 0x22, 0x03, 0x68, 0x25, 0x31, 0x0d, 0x46, 0xc1, 0xb8, 0x17, 0xb6, 0x92, 0x98,
	0x7d, 0x0b, 0xc4, 0x00, 0x7e, 0x50, 0x91, 0x92, 0x0e, 0x75, 0x0a, 0x9d, 0x42, 0xf2, 0x7c, 0x3e,
	0xb3, 0x48, 0x6b, 0x91, 0x21, 0x74, 0x15, 0xa2, 0xe7, 0x33, 0xda, 0xc2, 0x88, 0xb7, 0xd9, 0x3f,
	0x7b, 0xd0, 0x31, 0xa9, 0x6a, 0xb0, 0xa0, 0x0e, 0x23, 0x14, 0xf6, 0xf9, 0x0d, 0x17, 0x65, 0x06,
	0x67, 0x56, 0x1e, 0xdd, 0xad, 0x3d, 0x4a, 0x61, 0x7f, 0x99, 0xa5, 0xeb, 0x48, 0x6c, 0xe8, 0x9e,
	0xf9, 0xc2, 0x9a, 0xe4, 0x5d, 0xe8, 0xdd, 0x70, 0x51, 0xf0, 0x8b, 0x44, 0x6d, 0x68, 0x1b, 0x63,
	0xa5, 0xc3, 0x47, 0xbf, 0x8f, 0x52, 0x4e, 0x3b, 0x95, 0xa8, 0x76, 0xe8, 0xa8, 0x54, 0x51, 0xae,
	0x66, 0x91, 0xe2, 0x74, 0xdf, 0x44, 0xbd, 0xc3, 0x47, 0x2f, 0x93, 0x94, 0xd3, 0x6e, 0x25, 0xaa,
	0x1d, 0x3a, 0x8a, 0x45, 0x63, 0xe6, 0x9e, 0x89, 0x7a, 0x87, 0xee, 0x23, 0x4a, 0xb3, 0x42, 0x28,
	0x0a, 0xa3, 0x60, 0x1c, 0x84, 0xd6, 0x22, 0xc7, 0xd0, 0x4e, 0xd2, 0xe8, 0x9a, 0xd3, 0x3e, 0x7e,
	0x61, 0x0c, 0x42, 0x60, 0x6f, 0x95, 0x5d, 0x67, 0xf4, 0x00, 0x9d, 0xf8, 0x9b, 0x8c, 0xa0, 0xbf,
	0x2e, 0xf2, 0xe5, 0xaf, 0x91, 0xe4, 0xf1, 0x73, 0x41, 0x0f, 0x47, 0xc1, 0x78, 0x37, 0xac, 0xba,
	0x0c, 0xc3, 0x29, 0xff, 0x29, 0x13, 0x9c, 0x0e, 0x1c, 0xc3, 0xc6, 0xd6, 0x19, 0x5f, 0x6b, 0xff,
	0x91, 0xc9, 0xa8, 0x7f, 0x6b, 0xfc, 0x4d, 0x22, 0x13, 0x95, 0xe5, 0x92, 0xde, 0x1b, 0x05, 0xe3,
	0x76, 0xe8, 0x6d, 0xdd, 0x4d, 0xa4, 0x14, 0x17, 0x31, 0xe7, 0x92, 0xde, 0xc7, 0x60, 0xe9, 0xc0,
	0x79, 0x89, 0x18, 0x59, 0x22, 0x76, 0x5e, 0xc6, 0xb4, 0x11, 0x64, 0xe8, 0x81, 0x8f, 0x20, 0x3f,
	0x1f, 0xc2, 0xc0, 0xcc, 0xfb, 0xd2, 0xd5, 0x78, 0x8c, 0x80, 0x86, 0x97, 0x3c, 0x06, 0x30, 0x1e,
	0xc4, 0x9c, 0x20, 0xa6, 0xe2, 0xd1, 0x55, 0x2f, 0x8b, 0x3c, 0xe7, 0x62, 0xb9, 0xa1, 0xa7, 0xa6,
	0x4b, 0x67, 0xb3, 0x9f, 0xe1, 0xe8, 0x89, 0x2b, 0x52, 0x6b, 0xb7, 0x90, 0x84, 0xc1, 0x81, 0x6d,
	0xea, 0x02, 0xe9, 0x0f, 0xb0, 0x97, 0x9a, 0x8f, 0x7c, 0x00, 0x87, 0xae, 0x37, 0x03, 0x6a, 0x21,
	0xa8, 0xee, 0x64, 0xdf, 0xc1, 0xc9, 0x45, 0x26, 0x5e, 0x26, 0x79, 0xea, 0xde, 0xd8, 0x52, 0x76,
	0xdc, 0x50, 0x76, 0xec, 0xf5, 0x1b, 0x5b, 0x61, 0x5b, 0x8b, 0x7d, 0x05, 0xdd, 0x90, 0xcb, 0x75,
	0x26, 0x24, 0x6a, 0x43, 0x62, 0xb1, 0x6e, 0xb1, 0x8c, 0xa5, 0xb9, 0x4c, 0xb9, 0x94, 0x5a, 0x1d,
	0x76, 0x2b, 0xac, 0xc9, 0x42, 0x20, 0x2f, 0xf2, 0x44, 0xa8, 0xfa, 0x1a, 0x3f, 0x82, 0x9e, 0x79,
	0x77, 0x91, 0x6c, 0x17, 0x72, 0x0e, 0x7d, 0xd7, 0x8e, 0x0e, 0x9b, 0x84, 0xe0, 0x5c, 0xf3, 0x98,
	0xfd, 0x19, 0x40, 0xef, 0x6b, 0xdc, 0x3a, 0xf1, 0x32, 0x23, 0x67, 0x00, 0x28, 0xde, 0x85, 0xd0,
	0x72, 0x0e, 0x9a, 0x72, 0x3e, 0x03, 0x40, 0xe5, 0x2f, 0x62, 0xad, 0x81, 0x56, 0x73, 0x53, 0x7c,
	0x58, 0xeb, 0xcf, 0x6e, 0x6e, 0x65, 0x55, 0x8e, 0xa1, 0x8d, 0x3b, 0x67, 0x57, 0xd7, 0x18, 0x5a,
	0x72, 0x59, 0x7e, 0x1d, 0x89, 0xe4, 0x35, 0xcf, 0xdd, 0xe2, 0x7a, 0x87, 0xae, 0xdf, 0x36, 0x27,
	0xca, 0xd5, 0xb5, 0xba, 0xd0, 0x25, 0xb1, 0xbf, 0x02, 0x00, 0xc3, 0x07, 0x36, 0xf0, 0x0e, 0x74,
	0x4d, 0x03, 0x9e, 0x0b, 0x7b, 0x53, 0x62, 0xf2, 0x1e, 0x1c, 0xf8, 0xb5, 0x59, 0x5c, 0x6d, 0x6c,
	0xf9, 0xe5, 0x2a, 0x3d, 0xdd, 0xd4, 0x21, 0x99, 0xc0, 0x16, 0x1a, 0xdb, 0xf6, 0x09, 0x74, 0x1d,
	0x7b, 0xd8, 0x47, 0x7f, 0x7a, 0x6f, 0x62, 0x0e, 0xec, 0xc4, 0xe9, 0x23, 0xf4, 0x08, 0xf2, 0x3e,
	0x1c, 0xba, 0xf2, 0x8b, 0xf4, 0xca, 0x37, 0x78, 0x60, 0x1b, 0x40, 0x1f, 0xfb, 0x1c, 0xba, 0xee,
	0x53, 0xcd, 0x11, 0x4f, 0xa3, 0x64, 0x65, 0x8b, 0x37, 0x86, 0x5e, 0x63, 0x6c, 0xdf, 0x94, 0x8c,
	0xbf, 0xd9, 0x6f, 0xf0, 0xa0, 0x26, 0x06, 0xab, 0xaa, 0x8f, 0xa0, 0x8d, 0x0d, 0x63, 0x82, 0xfe,
	0xf4, 0xbe, 0x2b, 0xce, 0xcf, 0x38, 0x34, 0x71, 0xf2, 0x31, 0x74, 0x4c, 0x15, 0x98, 0xb5, 0x3f,
	0x25, 0x0e, 0x59, 0xb2, 0x19, 0x5a, 0x04, 0xfb, 0x02, 0x4e, 0xf1, 0xad, 0x27, 0xab, 0x95, 0x89,
	0xca, 0xbb, 0x88, 0x8f, 0xfd, 0x1d, 0xc0, 0xa0, 0xfc, 0xe4, 0xed, 0xcc, 0x67, 0x52, 0xbd, 0x60,
	0x7b, 0xa3, 0xdd, 0x5b, 0x07, 0x54, 0xb9, 0x69, 0x77, 0x9a, 0x50, 0x0e, 0x0f, 0xb7, 0xfa, 0xff,
	0xbf, 0x7c, 0x4f, 0x1a, 0x7c, 0x9f, 0xfa, 0xaa, 0x6a, 0x0c, 0x39, 0xce, 0xa7, 0xff, 0xb6, 0xa0,
	0xf5, 0xfc, 0x47, 0xf2, 0x25, 0x0c, 0x9e, 0x71, 0x3b, 0x64, 0xf9, 0x74, 0x33, 0x9f, 0x91, 0x93,
	0xfa, 0xa0, 0xec, 0x24, 0x86, 0x83, 0xba, 0x9b, 0xed, 0x7c, 0x1a, 0x90, 0x6f, 0x80, 0x3c, 0xe3,
	0xaa, 0x79, 0x1b, 0xdf, 0x90, 0xe0, 0x61, 0x93, 0x26, 0x8b, 0x67, 0x3b, 0x64, 0x06, 0x47, 0x8d,
	0x1b, 0x48, 0xce, 0x1c, 0xfa, 0xd6, 0xe3, 0x38, 0xf4, 0x9c, 0x3b, 0xa2, 0xd8, 0x0e, 0x79, 0x61,
	0x15, 0xdb, 0xbc, 0xa3, 0x0e, 0xba, 0x7d, 0xdb, 0x86, 0x8f, 0x6e, 0x8d, 0xf9, 0x8c, 0xbf, 0x94,
	0x73, 0xa9, 0x27, 0x95, 0xe4, 0x71, 0xed, 0xcb, 0x2d, 0xe1, 0x0e, 0xcf, 0xdf, 0x18, 0x77, 0xd9,
	0xaf, 0x3a, 0xf8, 0xff, 0xe9, 0xb3, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc5, 0xcb, 0x7e, 0x90,
	0x4b, 0x09, 0x00, 0x00,
}
